# this file was generated by the ./hack/generateSystems.js script
# do not edit this file as it'll most likely be overwritten on next invocation
{fetchzip}: {
  x86_64-linux = fetchzip {
    url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/6947b69d47deef74e7066f6b18a40a9e2058c8d7/code-insider-x64-1747287038.tar.gz";
    hash = "sha256-Rm7wBEjaXuRYUUQuGX0s+3uC4DsG3OQsjJMCD/3pNmM=";
  };
  aarch64-linux = fetchzip {
    url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/6947b69d47deef74e7066f6b18a40a9e2058c8d7/code-insider-arm64-1747287135.tar.gz";
    hash = "sha256-kpdc2E5JRaQ6viNC3G+H5Rbf2g0r2xf1c4DE8pmYzFg=";
  };
  armv7l-linux = fetchzip {
    url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/6947b69d47deef74e7066f6b18a40a9e2058c8d7/code-insider-armhf-1747287219.tar.gz";
    hash = "sha256-yC4ttyQvRs3rrkqc2KxjpS9NrHWIhoGz9I1hJqViGAw=";
  };
  x86_64-darwin = fetchzip {
    url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/6947b69d47deef74e7066f6b18a40a9e2058c8d7/VSCode-darwin.zip";
    hash = "sha256-pSQID3Mo4IkGCkVmlS/GwfWFmcnoyeFDEwL15NoWXnc=";
  };
  aarch64-darwin = fetchzip {
    url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/6947b69d47deef74e7066f6b18a40a9e2058c8d7/VSCode-darwin-arm64.zip";
    hash = "sha256-dtvdASJTdLerzdQnNXJUSaAbuwR2ORZsgg6+W1zr6cY=";
  };
}
