# this file was generated by the ./hack/generateSystems.js script
# do not edit this file as it'll most likely be overwritten on next invocation
{
  fetchzip,
  fetchurl,
}: {
  x86_64-linux = fetchzip {
    url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/ebb335fad028ca0f3582e822d14a1bb9109725e7/code-insider-x64-1780550280.tar.gz";
    hash = "sha256-7xsT+Mq72PM87+yOLjfeEWUEMGM/m1GG9WsIP3p+S8Q=";
  };
  aarch64-linux = fetchzip {
    url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/ebb335fad028ca0f3582e822d14a1bb9109725e7/code-insider-arm64-1780550271.tar.gz";
    hash = "sha256-3KzGDYDWUWHBWlDB/JNianRVp1ag2sRQUvjd7ZtpDDE=";
  };
  armv7l-linux = fetchzip {
    url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/ebb335fad028ca0f3582e822d14a1bb9109725e7/code-insider-armhf-1780550274.tar.gz";
    hash = "sha256-3FOHmvKradn2bofO+S1TXkkEHPPK4mMgplrKgk7WgrY=";
  };
  x86_64-darwin = fetchurl {
    url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/ebb335fad028ca0f3582e822d14a1bb9109725e7/VSCode-darwin-x64.dmg";
    hash = "sha256-AHnVHopAdC64UjImVDNN+SiO+mT1Oge+pTBvIhL4Zgw=";
  };
  aarch64-darwin = fetchurl {
    url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/ebb335fad028ca0f3582e822d14a1bb9109725e7/VSCode-darwin-arm64.dmg";
    hash = "sha256-cHXO7bv3Dxk4LZj8ai61o5HtGfsaeMbixvQByOsJ2L0=";
  };
}
