# this file was generated by the ./hack/generateSystems.js script
# do not edit this file as it'll most likely be overwritten on next invocation
{
  fetchzip,
  fetchurl,
}: {
  x86_64-linux = fetchzip {
    url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/37a7dda8100be458b06583283b1d7c88b787da69/code-insider-x64-1789433364.tar.gz";
    hash = "sha256-EQUvUWxs4/roHncf+1PJFsLkH2z93mxIi4oZJBi27ZU=";
  };
  aarch64-linux = fetchzip {
    url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/37a7dda8100be458b06583283b1d7c88b787da69/code-insider-arm64-1789433361.tar.gz";
    hash = "sha256-4WzEIkAgFaSn2xKJR4ib7/uvhK+zXd0T61q55bkt580=";
  };
  armv7l-linux = fetchzip {
    url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/37a7dda8100be458b06583283b1d7c88b787da69/code-insider-armhf-1789433356.tar.gz";
    hash = "sha256-KGiTe/nSwB/WqMmORY6R7Tv74WlYtegvqRq/yA7BQS0=";
  };
  x86_64-darwin = fetchurl {
    url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/37a7dda8100be458b06583283b1d7c88b787da69/VSCode-darwin-x64.dmg";
    hash = "sha256-CFiAPJKVxys/Rsg/u608P63QF/JZn1L0bSayViZdGp0=";
  };
  aarch64-darwin = fetchurl {
    url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/37a7dda8100be458b06583283b1d7c88b787da69/VSCode-darwin-arm64.dmg";
    hash = "sha256-xN89vebvWsD2tsTRRXLlDumdI0aViM/gtEWsrf6x7xE=";
  };
}
