name: Build
on:
    workflow_dispatch: {}
    schedule:
        - cron: "0 8 * * *"
    push:
        branches:
            - master
        paths:
            - 'src/**/*.nix'
            - 'flake.nix'
            - 'systems.nix'
            - 'crossbuild.nix'
            - 'hack/'
permissions:
    # Allow the pipeline to commit any changes to the repository
    contents: write
jobs:
    update:
        name: "Update / `systems.nix`"
        runs-on: ubuntu-latest
        if: ${{github.repository == 'auguwu/vscode-insiders-nix'}}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 22.x
            - uses: cachix/install-nix-action@v31
              with:
                extra_nix_config: |
                    experimental-features = nix-command flakes

            - run: ./hack/generateSystems.js
            - uses: EndBug/add-and-commit@v9
              with:
                author_name: "Noel Towa"
                default_author: user_info
                author_email: cutie@floofy.dev
                message: '[skip ci] Update Insiders build :sparkles:'
                push: true
    build:
        name: "Build [${{matrix.nix}}: ${{matrix.system}}]"
        runs-on: ${{matrix.runner}}
        if: ${{github.repository == 'auguwu/vscode-insiders-nix' && github.event_name != 'pull_request' }}
        needs: update
        strategy:
            fail-fast: false
            matrix:
                runner: [macos-latest, ubuntu-latest]
                nix: [x86_64-darwin, aarch64-darwin, x86_64-linux, aarch64-linux]
                include:
                    - nix: x86_64-darwin
                      system: x86_64-apple-darwin

                    - nix: aarch64-darwin
                      system: x86_64-apple-darwin

                    - nix: x86_64-linux
                      system: x86_64-unknown-linux-gnu

                    - nix: aarch64-linux
                      system: aarch64-unknown-linux-gnu
        steps:
            - uses: actions/checkout@v4
            - uses: cachix/install-nix-action@v31
              with:
                extra_nix_config: |
                    experimental-features = nix-command flakes

            # TODO(@auguwu): switch to `nix.noel.pink` once avaliable
            - uses: cachix/cachix-action@v16
              with:
                name: noel
                authToken: ${{secrets.CACHIX_AUTH_TOKEN}}

            - run: nix build --file ./crossbuild.nix --argstr system "${{matrix.system}}"
